site_name: Banking PiggyBank Spec
site_description: Спецификация и ТЗ для банковского сервиса автонакоплений "Копилка"
site_author: Ksenia
site_url: https://ubivator5000.github.io/banking-piggybank-spec/

# Настройка стильного оформления (Material Theme)
theme:
  name: material
  language: ru
  icon:
    logo: material/bank-outline
    repo: fontawesome/brands/github
  palette:
    # Светлая тема
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему
    # Тёмная тема
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - bpmn-js 
  
# Подключение плагинов и красивых расширений Markdown
markdown_extensions:
  - admonition                  # Красивые плашки/инфоблоки (!!! note, !!! warning)
  - attr_list
  - md_in_html
  - pymdownx.details            # Сворачиваемые блоки <details>
  - pymdownx.superfences:       # Поддержка Mermaid диаграмм и подсветки
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Навигационное меню сайта
nav:
  - Бизнес-контекст: 01-business-context.md
  - Функциональные требования: 02-functional-reqs.md
  - Модели процессов: 03-process-models.md
  - Архитектура и API: 04-architecture-api.md
  - Модель данных: 05-data-model.md
  - NFR и System Design: 06-non-functional.md